### ISSUE TITLE
Publish it on pub.dev

### ISSUE THREAD

**Issue by Skyost** [synw/nodecommander#1]
Hello,

Would it be possible for you to publish this project on pub.dev ?

**Comment by Robert3141** [comment]
currently to import it use this format in pubspec.yaml:
```
nodecommander: 
    git:
      url: https://github.com/synw/nodecommander.git
```
 as opposed to the standard method of import:
```
wifi: ^0.1.5
```

**Comment by synw** [comment]
Reopening, it should be published at some point you are right

**Comment by Robert3141** [comment]
> Reopening, it should be published at some point you are right

Thanks for the amazing work you did on this library. I discovered it and it did almost all I wanted. However it didn't allow two way data transfer so I cherry picked your code to make my own fudge of a [library](https://github.com/Robert3141/client_server_lan). I published it to pub.dev. Please can I have some feedback from your professional talent

**Comment by synw** [comment]
https://pub.dev/packages/nodecommander
